-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Sqlite_stat1_row exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Api.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)


rowid : SelectionSet Int Api.Object.Sqlite_stat1_row
rowid =
  Object.selectionForField "Int" "rowid" [] (Decode.int)


tbl : SelectionSet (Maybe String) Api.Object.Sqlite_stat1_row
tbl =
  Object.selectionForField "(Maybe String)" "tbl" [] (Decode.string |> Decode.nullable)


idx : SelectionSet (Maybe String) Api.Object.Sqlite_stat1_row
idx =
  Object.selectionForField "(Maybe String)" "idx" [] (Decode.string |> Decode.nullable)


stat : SelectionSet (Maybe String) Api.Object.Sqlite_stat1_row
stat =
  Object.selectionForField "(Maybe String)" "stat" [] (Decode.string |> Decode.nullable)
