-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Tasks_deletable_row exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Api.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)


{-| 
-}
ulid : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
ulid =
  Object.selectionForField "(Maybe String)" "ulid" [] (Decode.string |> Decode.nullable)


{-| 
-}
body : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
body =
  Object.selectionForField "(Maybe String)" "body" [] (Decode.string |> Decode.nullable)


{-| 
-}
modified_utc : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
modified_utc =
  Object.selectionForField "(Maybe String)" "modified_utc" [] (Decode.string |> Decode.nullable)


{-| 
-}
awake_utc : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
awake_utc =
  Object.selectionForField "(Maybe String)" "awake_utc" [] (Decode.string |> Decode.nullable)


{-| 
-}
ready_utc : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
ready_utc =
  Object.selectionForField "(Maybe String)" "ready_utc" [] (Decode.string |> Decode.nullable)


{-| 
-}
waiting_utc : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
waiting_utc =
  Object.selectionForField "(Maybe String)" "waiting_utc" [] (Decode.string |> Decode.nullable)


{-| 
-}
review_utc : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
review_utc =
  Object.selectionForField "(Maybe String)" "review_utc" [] (Decode.string |> Decode.nullable)


{-| 
-}
due_utc : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
due_utc =
  Object.selectionForField "(Maybe String)" "due_utc" [] (Decode.string |> Decode.nullable)


{-| 
-}
closed_utc : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
closed_utc =
  Object.selectionForField "(Maybe String)" "closed_utc" [] (Decode.string |> Decode.nullable)


{-| 
-}
state : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
state =
  Object.selectionForField "(Maybe String)" "state" [] (Decode.string |> Decode.nullable)


{-| 
-}
group_ulid : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
group_ulid =
  Object.selectionForField "(Maybe String)" "group_ulid" [] (Decode.string |> Decode.nullable)


{-| 
-}
repetition_duration : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
repetition_duration =
  Object.selectionForField "(Maybe String)" "repetition_duration" [] (Decode.string |> Decode.nullable)


{-| 
-}
recurrence_duration : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
recurrence_duration =
  Object.selectionForField "(Maybe String)" "recurrence_duration" [] (Decode.string |> Decode.nullable)


{-| 
-}
tags : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
tags =
  Object.selectionForField "(Maybe String)" "tags" [] (Decode.string |> Decode.nullable)


{-| 
-}
notes : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
notes =
  Object.selectionForField "(Maybe String)" "notes" [] (Decode.string |> Decode.nullable)


{-| 
-}
priority : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
priority =
  Object.selectionForField "(Maybe String)" "priority" [] (Decode.string |> Decode.nullable)


{-| 
-}
user : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
user =
  Object.selectionForField "(Maybe String)" "user" [] (Decode.string |> Decode.nullable)


{-| 
-}
metadata : SelectionSet (Maybe String) Api.Object.Tasks_deletable_row
metadata =
  Object.selectionForField "(Maybe String)" "metadata" [] (Decode.string |> Decode.nullable)
