-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Task_to_task_row exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Api.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)


rowid : SelectionSet Int Api.Object.Task_to_task_row
rowid =
  Object.selectionForField "Int" "rowid" [] (Decode.int)


ulid : SelectionSet String Api.Object.Task_to_task_row
ulid =
  Object.selectionForField "String" "ulid" [] (Decode.string)


source_task_ulid : SelectionSet String Api.Object.Task_to_task_row
source_task_ulid =
  Object.selectionForField "String" "source_task_ulid" [] (Decode.string)


target_task_ulid : SelectionSet String Api.Object.Task_to_task_row
target_task_ulid =
  Object.selectionForField "String" "target_task_ulid" [] (Decode.string)


relation : SelectionSet String Api.Object.Task_to_task_row
relation =
  Object.selectionForField "String" "relation" [] (Decode.string)
