[changelog]
header = ""
body = """
{% if version %}\
  {# Only add unreleased changes #}\
{% else %}\
  ## {{ now() | date(format="%Y-%m-%d") }} - [?????)](<REPO>/releases/tag/v?????)
  {% if previous %}\
    {% if previous.commit_id and commit_id %}
      [{{ previous.commit_id | truncate(length=7, end="") }}]({{ previous.commit_id }})...\
          [{{ commit_id | truncate(length=7, end="") }}]({{ commit_id }})
    {% endif %}\
  {% endif %}\
  {% for group, commits in commits | group_by(attribute="group") %}
    {% if group != "_discard_" %}\
      #### {{ group | striptags | upper_first }}
      {% for commit in commits %}
          - {{ commit.message | split(pat="\n") | first | upper_first | trim }} \
              ([{{ commit.id | truncate(length=7, end="") }}](<REPO>/commit/{{ commit.id }}))\
            {% if commit.footers %}\
              {% for footer in commit.footers -%}
                  , {{ footer.token }}{{ footer.separator }}{{ footer.value }}\
              {% endfor %}\
            {% endif %}\
      {% endfor %}
    {% endif %}
  {% endfor %}\n
{% endif %}\
"""
footer = ""
trim = true
postprocessors = [
  { pattern = '<REPO>', replace = "https://github.com/ad-si/TaskLite" },
]
output = "_todo_changelog.md"

[git]
conventional_commits = false # https://www.conventionalcommits.org
filter_unconventional = false
split_commits = true
commit_preprocessors = [
  # Replace issue numbers
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))" },
  # Check spelling of the commit with https://github.com/crate-ci/typos
  # If the spelling is incorrect, it will be automatically fixed.
  # { pattern = '.*', replace_command = 'typos --write-changes -' },
]
# Using HTML tags to set the sort order of the groups
commit_parsers = [
  { message = "^Webapp:", group = "<!-- 1 -->🌐 Webapp" },
  { message = "^Docs:", group = "<!-- 2 -->📚 Documentation" },
  { message = "^CI:", group = "_discard_" },
  { message = ".*", group = "<!-- 0 -->💻 General" },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"
