[build]
command = "./netlify-build.sh"
publish = "docs"

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
