# WARNING: Later LTS versions don't seem to work with Beam
resolver: lts-20.26
packages:
  - huzzy
  - tasklite-core
  # - tasklite-app

extra-deps:
  - simple-sql-parser-0.6.0

  - github: ad-si/iso8601-duration
    commit: 15822155a51831fbcd75a3bb5cb608a731a0461b

allow-newer: true

# Build TaskLite in a container
# docker:
#   repo: fpco/stack-build

# Copy executable to new image
# image:
#   containers:
#     - base: haskell-datasette
#       name: adius/tasklite
#       entrypoints:
#         - tasklite
