resolver: lts-19.3
packages:
  - huzzy
  - tasklite-core
  - tasklite-server
  # - tasklite-api
  # - tasklite-app
  # - tasklite-web

extra-deps:
  - aeson-1.5.6.0

  - iso8601-duration-0.1.1.0

  - portable-lines-0.1

  - github: ad-si/ulid
    commit: 443b5d74d0f2abdc3879e8338cc4497d68e640df

  - github: JakeWheat/simple-sql-parser
    commit: 00433a26e8303c9e61359f406da5a2dbf1293fc8

  - github: protolude/protolude
    commit: 3e249724fd0ead27370c8c297b1ecd38f92cbd5b

extra-include-dirs:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi

allow-newer: true

# Build TaskLite in a container
# docker:
#   repo: fpco/stack-build

# Copy executable to new image
# image:
#   containers:
#     - base: haskell-datasette
#       name: adius/tasklite
#       entrypoints:
#         - tasklite
