resolver: lts-16.21
packages:
  - huzzy
  - tasklite-core
  - tasklite-server
  # - tasklite-api
  # - tasklite-app
  # - tasklite-web

extra-deps:
  - acid-state-0.16.0.1
  - dependent-map-0.2.4.0
  - dependent-sum-0.5
  - direct-sqlite-2.3.26
  - gi-gtk-declarative-0.4.2
  - gi-gtk-declarative-app-simple-0.4.1
  - iso8601-duration-0.1.1.0
  - portable-lines-0.1
  - sqlite-simple-0.4.18.0
  - ulid-0.3.0.0

  - github: haskell-beam/beam
    commit: efd464b079755a781c2bb7a2fc030d6c141bbb8a  # v0.9.0.0
    subdirs:
      - beam-core
      - beam-migrate
      - beam-sqlite

  - github: JakeWheat/simple-sql-parser
    commit: 00433a26e8303c9e61359f406da5a2dbf1293fc8

allow-newer: true

# Build TaskLite in a container
# docker:
#   repo: fpco/stack-build

# Copy executable to new image
# image:
#   containers:
#     - base: haskell-datasette
#       name: adius/tasklite
#       entrypoints:
#         - tasklite
