resolver: lts-20.5
packages:
  - huzzy
  - tasklite-core
  - tasklite-server
  # - tasklite-api
  # - tasklite-app
  # - tasklite-web

extra-deps:
  - github: ad-si/iso8601-duration
    commit: 15822155a51831fbcd75a3bb5cb608a731a0461b

  - github: JakeWheat/simple-sql-parser
    commit: 00433a26e8303c9e61359f406da5a2dbf1293fc8

extra-include-dirs:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi

allow-newer: true

# Build TaskLite in a container
# docker:
#   repo: fpco/stack-build

# Copy executable to new image
# image:
#   containers:
#     - base: haskell-datasette
#       name: adius/tasklite
#       entrypoints:
#         - tasklite
