-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Api.ScalarCodecs
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Json.Decode as Decode exposing (Decoder)
import Graphql.Internal.Encode as Encode exposing (Value)


type alias InsertTaskToTagOptionalArguments = { on_conflict : OptionalArgument (List Api.InputObject.Task_to_tag_upsert_on_conflict) }


type alias InsertTaskToTagRequiredArguments = { objects : (List Api.InputObject.Task_to_tag_insert_input) }


{-| Insert new rows in table "task_to_tag"

  - objects - Rows to be inserted
  - on_conflict - Specifies how to handle broken UNIQUE constraints

-}
insert_task_to_tag :
  (InsertTaskToTagOptionalArguments -> InsertTaskToTagOptionalArguments)
  -> InsertTaskToTagRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_tag_mutation_response
  -> SelectionSet decodesTo RootMutation
insert_task_to_tag fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { on_conflict = Absent }

    optionalArgs____ =
      [ Argument.optional "on_conflict" filledInOptionals____.on_conflict (Api.InputObject.encodeTask_to_tag_upsert_on_conflict |> Encode.list) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "insert_task_to_tag" (optionalArgs____ ++ [ Argument.required "objects" requiredArgs____.objects (Api.InputObject.encodeTask_to_tag_insert_input |> Encode.list) ]) (object____) (Basics.identity)


type alias InsertTaskToNoteOptionalArguments = { on_conflict : OptionalArgument (List Api.InputObject.Task_to_note_upsert_on_conflict) }


type alias InsertTaskToNoteRequiredArguments = { objects : (List Api.InputObject.Task_to_note_insert_input) }


{-| Insert new rows in table "task_to_note"

  - objects - Rows to be inserted
  - on_conflict - Specifies how to handle broken UNIQUE constraints

-}
insert_task_to_note :
  (InsertTaskToNoteOptionalArguments -> InsertTaskToNoteOptionalArguments)
  -> InsertTaskToNoteRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_note_mutation_response
  -> SelectionSet decodesTo RootMutation
insert_task_to_note fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { on_conflict = Absent }

    optionalArgs____ =
      [ Argument.optional "on_conflict" filledInOptionals____.on_conflict (Api.InputObject.encodeTask_to_note_upsert_on_conflict |> Encode.list) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "insert_task_to_note" (optionalArgs____ ++ [ Argument.required "objects" requiredArgs____.objects (Api.InputObject.encodeTask_to_note_insert_input |> Encode.list) ]) (object____) (Basics.identity)


type alias InsertTasksOptionalArguments = { on_conflict : OptionalArgument (List Api.InputObject.Tasks_upsert_on_conflict) }


type alias InsertTasksRequiredArguments = { objects : (List Api.InputObject.Tasks_insert_input) }


{-| Insert new rows in table "tasks"

  - objects - Rows to be inserted
  - on_conflict - Specifies how to handle broken UNIQUE constraints

-}
insert_tasks :
  (InsertTasksOptionalArguments -> InsertTasksOptionalArguments)
  -> InsertTasksRequiredArguments
  -> SelectionSet decodesTo Api.Object.Tasks_mutation_response
  -> SelectionSet decodesTo RootMutation
insert_tasks fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { on_conflict = Absent }

    optionalArgs____ =
      [ Argument.optional "on_conflict" filledInOptionals____.on_conflict (Api.InputObject.encodeTasks_upsert_on_conflict |> Encode.list) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "insert_tasks" (optionalArgs____ ++ [ Argument.required "objects" requiredArgs____.objects (Api.InputObject.encodeTasks_insert_input |> Encode.list) ]) (object____) (Basics.identity)


type alias InsertSqliteStat1OptionalArguments = { on_conflict : OptionalArgument (List Api.InputObject.Sqlite_stat1_upsert_on_conflict) }


type alias InsertSqliteStat1RequiredArguments = { objects : (List Api.InputObject.Sqlite_stat1_insert_input) }


{-| Insert new rows in table "sqlite_stat1"

  - objects - Rows to be inserted
  - on_conflict - Specifies how to handle broken UNIQUE constraints

-}
insert_sqlite_stat1 :
  (InsertSqliteStat1OptionalArguments -> InsertSqliteStat1OptionalArguments)
  -> InsertSqliteStat1RequiredArguments
  -> SelectionSet decodesTo Api.Object.Sqlite_stat1_mutation_response
  -> SelectionSet decodesTo RootMutation
insert_sqlite_stat1 fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { on_conflict = Absent }

    optionalArgs____ =
      [ Argument.optional "on_conflict" filledInOptionals____.on_conflict (Api.InputObject.encodeSqlite_stat1_upsert_on_conflict |> Encode.list) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "insert_sqlite_stat1" (optionalArgs____ ++ [ Argument.required "objects" requiredArgs____.objects (Api.InputObject.encodeSqlite_stat1_insert_input |> Encode.list) ]) (object____) (Basics.identity)


type alias InsertTaskToTaskOptionalArguments = { on_conflict : OptionalArgument (List Api.InputObject.Task_to_task_upsert_on_conflict) }


type alias InsertTaskToTaskRequiredArguments = { objects : (List Api.InputObject.Task_to_task_insert_input) }


{-| Insert new rows in table "task_to_task"

  - objects - Rows to be inserted
  - on_conflict - Specifies how to handle broken UNIQUE constraints

-}
insert_task_to_task :
  (InsertTaskToTaskOptionalArguments -> InsertTaskToTaskOptionalArguments)
  -> InsertTaskToTaskRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_task_mutation_response
  -> SelectionSet decodesTo RootMutation
insert_task_to_task fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { on_conflict = Absent }

    optionalArgs____ =
      [ Argument.optional "on_conflict" filledInOptionals____.on_conflict (Api.InputObject.encodeTask_to_task_upsert_on_conflict |> Encode.list) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "insert_task_to_task" (optionalArgs____ ++ [ Argument.required "objects" requiredArgs____.objects (Api.InputObject.encodeTask_to_task_insert_input |> Encode.list) ]) (object____) (Basics.identity)


type alias UpdateTaskToTagOptionalArguments =
  { set_ : OptionalArgument Api.InputObject.Task_to_tag_set_input
  , where_ : OptionalArgument Api.InputObject.Task_to_tag_filter
  }


{-| Update rows in table "task_to_tag"

  - set_ - Fields to be updated
  - where_ - Filter to select rows to be updated

-}
update_task_to_tag :
  (UpdateTaskToTagOptionalArguments -> UpdateTaskToTagOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Task_to_tag_mutation_response
  -> SelectionSet decodesTo RootMutation
update_task_to_tag fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent, where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTask_to_tag_set_input), Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTask_to_tag_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_task_to_tag" optionalArgs____ (object____) (Basics.identity)


type alias UpdateTaskToNoteOptionalArguments =
  { set_ : OptionalArgument Api.InputObject.Task_to_note_set_input
  , where_ : OptionalArgument Api.InputObject.Task_to_note_filter
  }


{-| Update rows in table "task_to_note"

  - set_ - Fields to be updated
  - where_ - Filter to select rows to be updated

-}
update_task_to_note :
  (UpdateTaskToNoteOptionalArguments -> UpdateTaskToNoteOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Task_to_note_mutation_response
  -> SelectionSet decodesTo RootMutation
update_task_to_note fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent, where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTask_to_note_set_input), Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTask_to_note_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_task_to_note" optionalArgs____ (object____) (Basics.identity)


type alias UpdateTasksOptionalArguments =
  { set_ : OptionalArgument Api.InputObject.Tasks_set_input
  , where_ : OptionalArgument Api.InputObject.Tasks_filter
  }


{-| Update rows in table "tasks"

  - set_ - Fields to be updated
  - where_ - Filter to select rows to be updated

-}
update_tasks :
  (UpdateTasksOptionalArguments -> UpdateTasksOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Tasks_mutation_response
  -> SelectionSet decodesTo RootMutation
update_tasks fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent, where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTasks_set_input), Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTasks_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_tasks" optionalArgs____ (object____) (Basics.identity)


type alias UpdateSqliteStat1OptionalArguments =
  { set_ : OptionalArgument Api.InputObject.Sqlite_stat1_set_input
  , where_ : OptionalArgument Api.InputObject.Sqlite_stat1_filter
  }


{-| Update rows in table "sqlite_stat1"

  - set_ - Fields to be updated
  - where_ - Filter to select rows to be updated

-}
update_sqlite_stat1 :
  (UpdateSqliteStat1OptionalArguments -> UpdateSqliteStat1OptionalArguments)
  -> SelectionSet decodesTo Api.Object.Sqlite_stat1_mutation_response
  -> SelectionSet decodesTo RootMutation
update_sqlite_stat1 fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent, where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeSqlite_stat1_set_input), Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeSqlite_stat1_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_sqlite_stat1" optionalArgs____ (object____) (Basics.identity)


type alias UpdateTaskToTaskOptionalArguments =
  { set_ : OptionalArgument Api.InputObject.Task_to_task_set_input
  , where_ : OptionalArgument Api.InputObject.Task_to_task_filter
  }


{-| Update rows in table "task_to_task"

  - set_ - Fields to be updated
  - where_ - Filter to select rows to be updated

-}
update_task_to_task :
  (UpdateTaskToTaskOptionalArguments -> UpdateTaskToTaskOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Task_to_task_mutation_response
  -> SelectionSet decodesTo RootMutation
update_task_to_task fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent, where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTask_to_task_set_input), Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTask_to_task_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_task_to_task" optionalArgs____ (object____) (Basics.identity)


type alias DeleteTaskToTagOptionalArguments = { where_ : OptionalArgument Api.InputObject.Task_to_tag_filter }


{-| Delete rows in table "task_to_tag"

  - where_ - Filter to select rows to be deleted

-}
delete_task_to_tag :
  (DeleteTaskToTagOptionalArguments -> DeleteTaskToTagOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Task_to_tag_mutation_response
  -> SelectionSet decodesTo RootMutation
delete_task_to_tag fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTask_to_tag_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "delete_task_to_tag" optionalArgs____ (object____) (Basics.identity)


type alias DeleteTaskToNoteOptionalArguments = { where_ : OptionalArgument Api.InputObject.Task_to_note_filter }


{-| Delete rows in table "task_to_note"

  - where_ - Filter to select rows to be deleted

-}
delete_task_to_note :
  (DeleteTaskToNoteOptionalArguments -> DeleteTaskToNoteOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Task_to_note_mutation_response
  -> SelectionSet decodesTo RootMutation
delete_task_to_note fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTask_to_note_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "delete_task_to_note" optionalArgs____ (object____) (Basics.identity)


type alias DeleteTasksOptionalArguments = { where_ : OptionalArgument Api.InputObject.Tasks_filter }


{-| Delete rows in table "tasks"

  - where_ - Filter to select rows to be deleted

-}
delete_tasks :
  (DeleteTasksOptionalArguments -> DeleteTasksOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Tasks_mutation_response
  -> SelectionSet decodesTo RootMutation
delete_tasks fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTasks_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "delete_tasks" optionalArgs____ (object____) (Basics.identity)


type alias DeleteSqliteStat1OptionalArguments = { where_ : OptionalArgument Api.InputObject.Sqlite_stat1_filter }


{-| Delete rows in table "sqlite_stat1"

  - where_ - Filter to select rows to be deleted

-}
delete_sqlite_stat1 :
  (DeleteSqliteStat1OptionalArguments -> DeleteSqliteStat1OptionalArguments)
  -> SelectionSet decodesTo Api.Object.Sqlite_stat1_mutation_response
  -> SelectionSet decodesTo RootMutation
delete_sqlite_stat1 fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeSqlite_stat1_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "delete_sqlite_stat1" optionalArgs____ (object____) (Basics.identity)


type alias DeleteTaskToTaskOptionalArguments = { where_ : OptionalArgument Api.InputObject.Task_to_task_filter }


{-| Delete rows in table "task_to_task"

  - where_ - Filter to select rows to be deleted

-}
delete_task_to_task :
  (DeleteTaskToTaskOptionalArguments -> DeleteTaskToTaskOptionalArguments)
  -> SelectionSet decodesTo Api.Object.Task_to_task_mutation_response
  -> SelectionSet decodesTo RootMutation
delete_task_to_task fillInOptionals____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { where_ = Absent }

    optionalArgs____ =
      [ Argument.optional "where" filledInOptionals____.where_ (Api.InputObject.encodeTask_to_task_filter) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "delete_task_to_task" optionalArgs____ (object____) (Basics.identity)


type alias UpdateTaskToTagByPkOptionalArguments = { set_ : OptionalArgument Api.InputObject.Task_to_tag_set_input }


type alias UpdateTaskToTagByPkRequiredArguments = { ulid : String }


{-| Update row in table "task_to_tag" by PK

  - set_ - Fields to be updated

-}
update_task_to_tag_by_pk :
  (UpdateTaskToTagByPkOptionalArguments -> UpdateTaskToTagByPkOptionalArguments)
  -> UpdateTaskToTagByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_tag_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
update_task_to_tag_by_pk fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTask_to_tag_set_input) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_task_to_tag_by_pk" (optionalArgs____ ++ [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ]) (object____) (Basics.identity)


type alias UpdateTaskToNoteByPkOptionalArguments = { set_ : OptionalArgument Api.InputObject.Task_to_note_set_input }


type alias UpdateTaskToNoteByPkRequiredArguments = { ulid : String }


{-| Update row in table "task_to_note" by PK

  - set_ - Fields to be updated

-}
update_task_to_note_by_pk :
  (UpdateTaskToNoteByPkOptionalArguments -> UpdateTaskToNoteByPkOptionalArguments)
  -> UpdateTaskToNoteByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_note_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
update_task_to_note_by_pk fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTask_to_note_set_input) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_task_to_note_by_pk" (optionalArgs____ ++ [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ]) (object____) (Basics.identity)


type alias UpdateTasksByPkOptionalArguments = { set_ : OptionalArgument Api.InputObject.Tasks_set_input }


type alias UpdateTasksByPkRequiredArguments = { ulid : String }


{-| Update row in table "tasks" by PK

  - set_ - Fields to be updated

-}
update_tasks_by_pk :
  (UpdateTasksByPkOptionalArguments -> UpdateTasksByPkOptionalArguments)
  -> UpdateTasksByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Tasks_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
update_tasks_by_pk fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTasks_set_input) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_tasks_by_pk" (optionalArgs____ ++ [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ]) (object____) (Basics.identity)


type alias UpdateSqliteStat1ByPkOptionalArguments = { set_ : OptionalArgument Api.InputObject.Sqlite_stat1_set_input }


type alias UpdateSqliteStat1ByPkRequiredArguments = { rowid : Int }


{-| Update row in table "sqlite_stat1" by PK

  - set_ - Fields to be updated

-}
update_sqlite_stat1_by_pk :
  (UpdateSqliteStat1ByPkOptionalArguments -> UpdateSqliteStat1ByPkOptionalArguments)
  -> UpdateSqliteStat1ByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Sqlite_stat1_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
update_sqlite_stat1_by_pk fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeSqlite_stat1_set_input) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_sqlite_stat1_by_pk" (optionalArgs____ ++ [ Argument.required "rowid" requiredArgs____.rowid (Encode.int) ]) (object____) (Basics.identity)


type alias UpdateTaskToTaskByPkOptionalArguments = { set_ : OptionalArgument Api.InputObject.Task_to_task_set_input }


type alias UpdateTaskToTaskByPkRequiredArguments = { ulid : String }


{-| Update row in table "task_to_task" by PK

  - set_ - Fields to be updated

-}
update_task_to_task_by_pk :
  (UpdateTaskToTaskByPkOptionalArguments -> UpdateTaskToTaskByPkOptionalArguments)
  -> UpdateTaskToTaskByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_task_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
update_task_to_task_by_pk fillInOptionals____ requiredArgs____ object____ =
  let
    filledInOptionals____ =
      fillInOptionals____ { set_ = Absent }

    optionalArgs____ =
      [ Argument.optional "_set" filledInOptionals____.set_ (Api.InputObject.encodeTask_to_task_set_input) ]
        |> List.filterMap Basics.identity
  in
  Object.selectionForCompositeField "update_task_to_task_by_pk" (optionalArgs____ ++ [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ]) (object____) (Basics.identity)


type alias DeleteTaskToTagByPkRequiredArguments = { ulid : String }


{-| Delete row in table "task_to_tag" by PK
-}
delete_task_to_tag_by_pk :
  DeleteTaskToTagByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_tag_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
delete_task_to_tag_by_pk requiredArgs____ object____ =
  Object.selectionForCompositeField "delete_task_to_tag_by_pk" [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ] (object____) (Basics.identity)


type alias DeleteTaskToNoteByPkRequiredArguments = { ulid : String }


{-| Delete row in table "task_to_note" by PK
-}
delete_task_to_note_by_pk :
  DeleteTaskToNoteByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_note_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
delete_task_to_note_by_pk requiredArgs____ object____ =
  Object.selectionForCompositeField "delete_task_to_note_by_pk" [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ] (object____) (Basics.identity)


type alias DeleteTasksByPkRequiredArguments = { ulid : String }


{-| Delete row in table "tasks" by PK
-}
delete_tasks_by_pk :
  DeleteTasksByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Tasks_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
delete_tasks_by_pk requiredArgs____ object____ =
  Object.selectionForCompositeField "delete_tasks_by_pk" [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ] (object____) (Basics.identity)


type alias DeleteSqliteStat1ByPkRequiredArguments = { rowid : Int }


{-| Delete row in table "sqlite_stat1" by PK
-}
delete_sqlite_stat1_by_pk :
  DeleteSqliteStat1ByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Sqlite_stat1_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
delete_sqlite_stat1_by_pk requiredArgs____ object____ =
  Object.selectionForCompositeField "delete_sqlite_stat1_by_pk" [ Argument.required "rowid" requiredArgs____.rowid (Encode.int) ] (object____) (Basics.identity)


type alias DeleteTaskToTaskByPkRequiredArguments = { ulid : String }


{-| Delete row in table "task_to_task" by PK
-}
delete_task_to_task_by_pk :
  DeleteTaskToTaskByPkRequiredArguments
  -> SelectionSet decodesTo Api.Object.Task_to_task_mutation_by_pk_response
  -> SelectionSet decodesTo RootMutation
delete_task_to_task_by_pk requiredArgs____ object____ =
  Object.selectionForCompositeField "delete_task_to_task_by_pk" [ Argument.required "ulid" requiredArgs____.ulid (Encode.string) ] (object____) (Basics.identity)
