-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)


type Closed_tasks_histogram_mutation_response
    = Closed_tasks_histogram_mutation_response


type Closed_tasks_histogram_row
    = Closed_tasks_histogram_row


type Tags_mutation_response
    = Tags_mutation_response


type Tags_row
    = Tags_row


type Task_to_note_mutation_response
    = Task_to_note_mutation_response


type Task_to_note_row
    = Task_to_note_row


type Task_to_tag_mutation_response
    = Task_to_tag_mutation_response


type Task_to_tag_row
    = Task_to_tag_row


type Tasks_head_mutation_response
    = Tasks_head_mutation_response


type Tasks_head_row
    = Tasks_head_row


type Tasks_mutation_response
    = Tasks_mutation_response


type Tasks_row
    = Tasks_row


type Tasks_view_mutation_response
    = Tasks_view_mutation_response


type Tasks_view_row
    = Tasks_view_row
