-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)

type Closed_tasks_histogram_row
  = Closed_tasks_histogram_row


type Sqlite_stat1_mutation_by_pk_response
  = Sqlite_stat1_mutation_by_pk_response


type Sqlite_stat1_mutation_response
  = Sqlite_stat1_mutation_response


type Sqlite_stat1_row
  = Sqlite_stat1_row


type Tags_row
  = Tags_row


type Task_to_note_mutation_by_pk_response
  = Task_to_note_mutation_by_pk_response


type Task_to_note_mutation_response
  = Task_to_note_mutation_response


type Task_to_note_row
  = Task_to_note_row


type Task_to_tag_mutation_by_pk_response
  = Task_to_tag_mutation_by_pk_response


type Task_to_tag_mutation_response
  = Task_to_tag_mutation_response


type Task_to_tag_row
  = Task_to_tag_row


type Task_to_task_mutation_by_pk_response
  = Task_to_task_mutation_by_pk_response


type Task_to_task_mutation_response
  = Task_to_task_mutation_response


type Task_to_task_row
  = Task_to_task_row


type Tasks_all_row
  = Tasks_all_row


type Tasks_deletable_row
  = Tasks_deletable_row


type Tasks_done_row
  = Tasks_done_row


type Tasks_modified_row
  = Tasks_modified_row


type Tasks_mutation_by_pk_response
  = Tasks_mutation_by_pk_response


type Tasks_mutation_response
  = Tasks_mutation_response


type Tasks_new_row
  = Tasks_new_row


type Tasks_notag_row
  = Tasks_notag_row


type Tasks_obsolete_row
  = Tasks_obsolete_row


type Tasks_old_row
  = Tasks_old_row


type Tasks_open_row
  = Tasks_open_row


type Tasks_overdue_row
  = Tasks_overdue_row


type Tasks_ready_row
  = Tasks_ready_row


type Tasks_recurring_row
  = Tasks_recurring_row


type Tasks_repeating_row
  = Tasks_repeating_row


type Tasks_row
  = Tasks_row


type Tasks_view_row
  = Tasks_view_row


type Tasks_waiting_row
  = Tasks_waiting_row
