-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)

type Closed_tasks_histogram_mutation_response
  = Closed_tasks_histogram_mutation_response


type Closed_tasks_histogram_row
  = Closed_tasks_histogram_row


type Tags_mutation_response
  = Tags_mutation_response


type Tags_row
  = Tags_row


type Task_to_note_mutation_response
  = Task_to_note_mutation_response


type Task_to_note_row
  = Task_to_note_row


type Task_to_tag_mutation_response
  = Task_to_tag_mutation_response


type Task_to_tag_row
  = Task_to_tag_row


type Tasks_all_mutation_response
  = Tasks_all_mutation_response


type Tasks_all_row
  = Tasks_all_row


type Tasks_deletable_mutation_response
  = Tasks_deletable_mutation_response


type Tasks_deletable_row
  = Tasks_deletable_row


type Tasks_done_mutation_response
  = Tasks_done_mutation_response


type Tasks_done_row
  = Tasks_done_row


type Tasks_modified_mutation_response
  = Tasks_modified_mutation_response


type Tasks_modified_row
  = Tasks_modified_row


type Tasks_mutation_response
  = Tasks_mutation_response


type Tasks_new_mutation_response
  = Tasks_new_mutation_response


type Tasks_new_row
  = Tasks_new_row


type Tasks_notag_mutation_response
  = Tasks_notag_mutation_response


type Tasks_notag_row
  = Tasks_notag_row


type Tasks_obsolete_mutation_response
  = Tasks_obsolete_mutation_response


type Tasks_obsolete_row
  = Tasks_obsolete_row


type Tasks_old_mutation_response
  = Tasks_old_mutation_response


type Tasks_old_row
  = Tasks_old_row


type Tasks_open_mutation_response
  = Tasks_open_mutation_response


type Tasks_open_row
  = Tasks_open_row


type Tasks_overdue_mutation_response
  = Tasks_overdue_mutation_response


type Tasks_overdue_row
  = Tasks_overdue_row


type Tasks_ready_mutation_response
  = Tasks_ready_mutation_response


type Tasks_ready_row
  = Tasks_ready_row


type Tasks_recurring_mutation_response
  = Tasks_recurring_mutation_response


type Tasks_recurring_row
  = Tasks_recurring_row


type Tasks_repeating_mutation_response
  = Tasks_repeating_mutation_response


type Tasks_repeating_row
  = Tasks_repeating_row


type Tasks_row
  = Tasks_row


type Tasks_view_mutation_response
  = Tasks_view_mutation_response


type Tasks_view_row
  = Tasks_view_row


type Tasks_waiting_mutation_response
  = Tasks_waiting_mutation_response


type Tasks_waiting_row
  = Tasks_waiting_row
