apiVersion: v1
kind: Service
metadata:
  name: tasklite-service
  labels:
    app: tasklite
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: tasklite
  type: NodePort
