-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Enum.Sqlite_stat1_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| This enum contains a variant for each column in the table
-}
type Sqlite_stat1_column
  = Rowid
  | Tbl
  | Idx
  | Stat


list : List Sqlite_stat1_column
list =
  [ Rowid, Tbl, Idx, Stat ]


decoder : Decoder Sqlite_stat1_column
decoder =
  Decode.string
    |> Decode.andThen
        (\string -> case string of
            "rowid" ->
              Decode.succeed Rowid
            "tbl" ->
              Decode.succeed Tbl
            "idx" ->
              Decode.succeed Idx
            "stat" ->
              Decode.succeed Stat
            _ ->
              Decode.fail ("Invalid Sqlite_stat1_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
        )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Sqlite_stat1_column -> String
toString enum____ =
  case enum____ of
    Rowid ->
      "rowid"
    Tbl ->
      "tbl"
    Idx ->
      "idx"
    Stat ->
      "stat"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Sqlite_stat1_column
fromString enumString____ =
  case enumString____ of
    "rowid" ->
      Just Rowid
    "tbl" ->
      Just Tbl
    "idx" ->
      Just Idx
    "stat" ->
      Just Stat
    _ ->
      Nothing
