-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Closed_tasks_histogram_row exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Api.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| 
-}
date_short : SelectionSet (Maybe String) Api.Object.Closed_tasks_histogram_row
date_short =
      Object.selectionForField "(Maybe String)" "date_short" [] (Decode.string |> Decode.nullable)


{-| 
-}
num_of_closed_tasks : SelectionSet (Maybe String) Api.Object.Closed_tasks_histogram_row
num_of_closed_tasks =
      Object.selectionForField "(Maybe String)" "num_of_closed_tasks" [] (Decode.string |> Decode.nullable)
