name: huzzy
version: 0.1.0.0
synopsis: Filters a list based on a fuzzy string search
homepage: https://github.com/ad-si/TaskLite/tree/master/huzzy
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber
category: Text, Fuzzy

description: |
  Please check out the readme on GitHub
  at https://github.com/ad-si/TaskLite/tree/master/huzzy#readme

extra-source-files:
  - README.md

dependencies:
  - base
  - monoid-subclasses
  - protolude

default-extensions:
  - ImportQualifiedPost
  - NoImplicitPrelude

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

library:
  source-dirs: src

tests:
  huzzy-test:
    main: tests.hs
    source-dirs: tests
    dependencies:
      - base
      - HUnit
      - huzzy
