name: tasklite-core
version: 0.3.0.0
github: "ad-si/TaskLite"
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber
category: CLI, Task, Todo
synopsis: CLI task / todo list manager with SQLite backend
description: |
  TaskLite is a CLI task / todo list manager with a SQLite backend.
  It is designed to be simple and easy to use,
  while still providing a powerful interface for managing tasks.
  It's heavily inspired by Taskwarrior and stems from my personal frustration
  with some of its design decisions.
  Check out https://tasklite.org/differences_taskwarrior
  for a full comparison.
extra-source-files:
  - README.md
data-files:
  - example-config.yaml

language: GHC2021

default-extensions:
  - DeriveAnyClass
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies
  - UndecidableInstances

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-orphans
  - -Wredundant-constraints
  - -Wunused-packages

dependencies:
  - base >= 4.18 && < 5
  - protolude >= 0.3

library:
  source-dirs: source
  dependencies:
    - aeson >= 2.2.1 && < 2.3
    - airgql >= 0.7.1.2 && < 0.8
    - ansi-terminal >= 0.11 && < 1.1
    - bytestring >= 0.11 && < 0.13
    - cassava >= 0.5.2 && < 0.6
    - colour >= 2.3 && < 2.4
    - directory >= 1.3 && < 1.4
    - editor-open >= 0.4 && < 0.7
    - exceptions >= 0.10 && < 0.11
    - file-embed >= 0.0.14 && < 0.1
    - filepath >= 1.4 && < 1.6
    - fuzzily >= 0.2 && < 0.3
    - generic-random >= 1.3 && < 1.6
    - githash >= 0.1.6 && < 0.2
    - hourglass >= 0.2.10 && < 0.3
    - hsemail >= 2.0 && < 2.3
    - iso8601-duration >= 0.1.1 && < 0.2
    - optparse-applicative >= 0.16 && < 0.19
    - parsec >= 3.1 && < 3.2
    - portable-lines >= 0.1 && < 0.2
    - prettyprinter >= 1.6 && < 1.8
    - prettyprinter-ansi-terminal >= 1.1 && < 1.2
    - process >= 1.6 && < 1.7
    - protolude >= 0.3 && < 0.4
    - QuickCheck >= 2.14 && < 2.15
    - quickcheck-instances >= 0.3.28 && < 0.4
    - random >= 1.2 && < 1.3
    - servant >= 0.18 && < 0.21
    - servant-blaze >= 0.7 && < 0.10
    - servant-multipart >= 0.11 && < 0.13
    - servant-server >= 0.18 && < 0.21
    - simple-sql-parser >= 0.6 && < 0.8
    - sqlite-simple >= 0.4 && < 0.5
    - syb >= 0.7 && < 0.8
    - text >= 1.2 && < 2.2
    - time >= 1.11 && < 1.15
    - ulid >= 0.3 && < 0.4
    - unix >= 2.8 && < 2.9
    - vector >= 0.12 && < 0.14
    - wai >= 3.2 && < 3.3
    - wai-cors >= 0.2 && < 0.3
    - wai-app-static >= 3.1 && < 3.2
    - warp >= 3.3 && < 3.5
    - yaml >= 0.11 && < 0.12
    - wai-extra >= 3.1 && < 3.2

tests:
  tasklite-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson
      - hourglass
      - hspec >= 2.11 && < 3.0
      - iso8601-duration
      - MissingH >= 1.4 && < 1.7
      - neat-interpolation >= 0.5 && < 0.6
      - sqlite-simple
      - tasklite-core
      - text
      - ulid
      - yaml

benchmarks:
  tasklite-bench:
    main: Main.hs
    source-dirs: benchmarks
    dependencies:
      - criterion >= 1.5 && < 1.7
