name: tasklite-app
version: 0.3.0.0
synopsis: ""
description: ""
homepage: https://github.com/ad-si/TaskLite#readme
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber
category: Web, App, Task, Todo, Desktop

extra-source-files:
  - readme.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - cassava
  - directory
  - filepath
  - gi-gtk
  - gi-gtk-declarative
  - gi-gtk-declarative-app-simple
  - hourglass
  - pipes
  - pipes-extras
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - protolude
  - simple-sql-parser
  - sqlite-simple
  - tasklite-core
  - text
  - ulid
  - unix
  - vector
  - yaml

default-extensions:
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - UndecidableInstances

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans
  - -threaded

library:
  source-dirs: source

executables:
  tasklite-app:
    source-dirs: app
    main: Main.hs
