name: tasklite-server
version: 0.1.0.0
synopsis: REST API server for TaskLite
description: |
  After signing up for an account, users can manage their ideas.
  Every idea contains 3 scores: Impact, Ease and Confidence.
  Each idea can be added, edited and deleted.
  All the ideas will be sorted by the average of all three scores.
  Every API call will return 10 ideas.
  When not using the service, users can log out of the system.
homepage: https://github.com/ad-si/TaskLite/tree/master/tasklite-server
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber
category: Web

dependencies:
  - aeson
  - attoparsec
  - base >= 4.7 && < 5
  - base-compat
  - blaze-html
  - blaze-markup
  - bytestring
  - directory
  - file-embed
  - filepath
  - githash
  - hourglass
  - http-media
  - iso8601-duration
  - lucid
  - mtl
  - optparse-applicative
  - prettyprinter
  - prettyprinter-ansi-terminal
  - protolude
  - servant
  - servant-server
  - sqlite-simple
  - string-conversions
  - tasklite-core
  - text
  - time
  - wai
  - warp
  - yaml

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

extra-source-files:
  - readme.md

executables:
  tasklite-server:
    source-dirs:      source
    main:             Main.hs
