name: Haskell Stack CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Stack
        uses: mstksg/setup-stack@v1

      - name: Install TaskLite CLI tool
        run: stack install tasklite-core

      - name: Upload Linux Release
        uses: actions/upload-artifact@v1
        with:
          path: /home/runner/.local/bin/tasklite
          name: tasklite_linux_x86_64.zip

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Stack
        uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true

      - name: Install TaskLite CLI tool
        run: stack install tasklite-core

      - name: Upload MacOS Release
        uses: actions/upload-artifact@v1
        with:
          path: /Users/runner/.local/bin/tasklite
          name: tasklite_macos_x86_64.zip

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Install stack
  #       shell: cmd
  #       run: choco install haskell-stack

  #     - name: Install dependencies
  #       run: stack install tasklite-core

  #     - name: Upload Windows Release
  #       uses: actions/upload-artifact@v1
  #       with:
  #         path: '%APPDATA%\local\bin\tasklite.exe'
  #         name: tasklite_windows_x86_64.exe

  # publish:
  #   needs: build
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Set env with output of `git describe`
  #       run: echo ::set-env name=GIT_DESCRIBE::$(git describe)
  #
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ env.GIT_DESCRIBE }}
  #         release_name: Release ${{ env.GIT_DESCRIBE }}
  #         body: ${{ github.event.commits[0].message }}
  #         draft: false
  #         prerelease: false
