name: Haskell Stack CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-work
        uses: actions/cache@v2
        with:
          path: .stack-work
          key: tasklite_stack-work_ubuntu
          restore-keys: tasklite_stack-work_ubuntu

      - name: Setup Stack
        uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true
          stack-no-global: true

      - name: Install TaskLite CLI tool
        run: stack install tasklite-core

      - name: Run test suite
        run: stack test

      - name: Test adding of tasks
        run: /home/runner/.local/bin/tasklite add Buy milk

      - name: Test listing of tasks
        run: /home/runner/.local/bin/tasklite

      - name: Upload Linux Release
        uses: actions/upload-artifact@v1
        with:
          path: /home/runner/.local/bin/tasklite
          name: tasklite_linux_x86_64.zip

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache .stack-work
        uses: actions/cache@v2
        with:
          path: .stack-work
          key: tasklite_stack-work_macos
          restore-keys: tasklite_stack-work_macos

      - name: Setup Stack
        uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true
          stack-no-global: true

      - name: Install TaskLite CLI tool
        run: stack install tasklite-core

      - name: Run test suite
        run: stack test

      - name: Test adding of tasks
        run: /Users/runner/.local/bin/tasklite add Buy milk

      - name: Test listing of tasks
        run: /Users/runner/.local/bin/tasklite

      - name: Upload MacOS Release
        uses: actions/upload-artifact@v1
        with:
          path: /Users/runner/.local/bin/tasklite
          name: tasklite_macos_x86_64.zip

  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: adius/tasklite:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Install stack
  #       shell: cmd
  #       run: choco install haskell-stack

  #     - name: Install dependencies
  #       run: stack install tasklite-core

  #     - name: Upload Windows Release
  #       uses: actions/upload-artifact@v1
  #       with:
  #         path: '%APPDATA%\local\bin\tasklite.exe'
  #         name: tasklite_windows_x86_64.exe

  # publish:
  #   needs: build
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Set env with output of `git describe`
  #       run: echo ::set-env name=GIT_DESCRIBE::$(git describe)
  #
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ env.GIT_DESCRIBE }}
  #         release_name: Release ${{ env.GIT_DESCRIBE }}
  #         body: ${{ github.event.commits[0].message }}
  #         draft: false
  #         prerelease: false
